services:
  db:
    image: postgres:17.0-alpine3.20
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    command: >
      /bin/sh -c "
      poetry run python manage.py collectstatic --noinput &&
      poetry run python manage.py makemigrations &&
      poetry run python manage.py migrate &&
      (poetry run python manage.py createsuperuser --no-input || true) &&
      poetry run python manage.py popular_tabelas &&
      poetry run python manage.py runserver 0.0.0.0:8000
      "
  

volumes:
  postgres_data:
