# Generated by Django 5.1.3 on 2024-11-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_demissao',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
